### ISSUE TITLE
Registered parameter for face watchlist need to be shown for update face registration window

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#34]
@EricBourque 
Test version: V1.0.0 released on 27th May.

Currently, when user click "Change", parameters entered when registration are not shown.
Could you  show the current registered parameter for user to understand current registration ?

![image](https://user-images.githubusercontent.com/102282918/171376394-0f22f758-e81f-485e-8c21-bd49da3346ed.png)

**Comment by PetrutVasile** [comment]
Fixed in the new version

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque  @PetrutVasile 
Test version：v1.0.0 release on 17th, August.

Current registered parameters are shown.(OK) 
But when clicking "Update" button, error is shown when "Validity period" is unchecked.(not OK)

![image](https://user-images.githubusercontent.com/102282918/189824274-448f58b9-8941-4f3d-9ec5-59074c467859.png)

According to the wireshark packet,  it's because the “delete_type” parameter does not exist in the request API, as in the message.
 
![image](https://user-images.githubusercontent.com/102282918/189824607-dd2ecb63-c54f-4d3e-9174-80fc035a8100.png)


Could you add "delete_type":"stop-matching" when Validity_period is unchecked Since “delete_type” is a mandatory parameter ?
You have implemented like this for new registration, but not implemented for updating.

**Comment by Yoshitaka-Fukushima** [comment]
Test version : V1.0.1 released on 5th, Oct.

I receive report from Eric that update face watchlist without "age" failed and investigated the cause.

Currently, when there are blank field , 
![image](https://user-images.githubusercontent.com/102282918/194221006-50655560-2b8b-429a-944a-4c7fefdc8764.png)

API sends the parameters for the blank field.
![image](https://user-images.githubusercontent.com/102282918/194221528-b71d7cf6-c0e8-4865-9f46-e09459a19669.png)

In this example, following parameter should not be included in API.
You have already implemented correctly for new registration.

"last name", ""
"age", ""
"remarks", ""

**Comment by EricBourque** [comment]
Fixed in 1.0.1

**Comment by Yoshitaka-Fukushima** [comment]
Test version: V1.0.1 released on 10th Oct.
Test result : not OK


When updating face watchlist as attached video, exception error occurs.　We tried 3 times and all the same result.



************** Outer Exception **************
Exception type:System.NullReferenceException
Exception message:Object reference not set to an instance of an object.
Exception source:ActiveGuardMilestonePlugins
Exception Target Site: c
   at ActiveGuardMilestonePlugins.Client.SetupWatchlists.c(Object , RoutedEventArgs )
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
Date and time:	10/11/2022 9:27:24 AM
Machine Name:	DESKTOP-HFH57FR
Processors count:	16
OS version:	Microsoft Windows NT 6.2.9200.0
64 bit OS:	True
64 bit process:	True
IP address:	::1 (DESKTOP-HFH57FR)
Current user:	DESKTOP-HFH57FR\Admin

[AGDRec_20221011_092746.zip](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/files/9749985/AGDRec_20221011_092746.zip)

**Comment by EricBourque** [comment]
Fixed in 1.0.2
