### ISSUE TITLE
Smart Client Crash - When uploading photo to Face Matching

### ISSUE THREAD

**Issue by SirTapp** [ORBNETSYS/i-PRO-Active-Guard-Public#88]
OS: Windows 10 Pro - latest updates
CPU: i7 9700K
RAM: 32GB
GPU: GTX 1660 Ti

Milestone XProtect Corp 2022 R3 - 
iPRO - Active Guard Server 1.6.1
iPRO - Active Guard Plugin - 1.5

Currently testing the uploading of a photo for face matching in the Smart Client, causes a complete crash of the Smart Client. 

Please see attached Windows and Milestone crash log:

  ************** Outer Exception **************
Exception type:System.Reflection.ReflectionTypeLoadException
Exception message:Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Exception source:mscorlib
Exception Target Site: GetTypes
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emgu.Util.Toolbox.GetInterfaceImplementationFromAssembly[T]()
   at Emgu.CV.NativeMatFileIO.ReadFileToMat(String fileName, Mat mat, ImreadModes loadType)
   at Emgu.CV.Mat..ctor(String fileName, ImreadModes loadType)
   at Emgu.CV.UMat..ctor(String fileName, ImreadModes loadType)
   at ActiveGuardMilestonePlugins.Client.UploadFace.btnUploadFile_Click(Object sender, RoutedEventArgs e) in C:\Users\ericb\source\repos\ORBNETSYS\i-PRO Active Guard\ActiveGuardMilestonePlugins\Client\UploadFace.xaml.cs:line 139
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
Date and time:	24/02/2023 11:19:25 AM
Machine Name:	TECHOFFICE
Processors count:	8
OS version:	Microsoft Windows NT 6.2.9200.0
64 bit OS:	True
64 bit process:	True
IP address:	fe80::15a6:6df3:fb08:bb37%6 (TechOffice)
Current user:	TECHOFFICE\VIX

************** Outer Exception **************
Exception type:System.Reflection.ReflectionTypeLoadException
Exception message:Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Exception source:mscorlib
Exception Target Site: GetTypes
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emgu.Util.Toolbox.GetInterfaceImplementationFromAssembly[T]()
   at Emgu.CV.NativeMatFileIO.ReadFileToMat(String fileName, Mat mat, ImreadModes loadType)
   at Emgu.CV.Mat..ctor(String fileName, ImreadModes loadType)
   at Emgu.CV.UMat..ctor(String fileName, ImreadModes loadType)
   at ActiveGuardMilestonePlugins.Client.UploadFace.btnUploadFile_Click(Object sender, RoutedEventArgs e) in C:\Users\ericb\source\repos\ORBNETSYS\i-PRO Active Guard\ActiveGuardMilestonePlugins\Client\UploadFace.xaml.cs:line 139
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
Date and time:	24/02/2023 11:19:25 AM
Machine Name:	TECHOFFICE
Processors count:	8
OS version:	Microsoft Windows NT 6.2.9200.0
64 bit OS:	True
64 bit process:	True
IP address:	fe80::15a6:6df3:fb08:bb37%6 (TechOffice)
Current user:	TECHOFFICE\VIX

**Comment by EricBourque** [comment]
Hi SirTapp,

Sorry for epicly slow response time, it slipped past us.
We are not able to reproduce this.
Are you still having the issue? We use OpenCV for the face detection in the face upload feature. Your specs look good. We could try to debug if you can provide remote access. Send us an email at support@orbnetsys.com
Try opeing the Smart Client as Administrator just to see if it changes anything. Also try to uninstall and re-install the plugin in the default install path to see if anything happens.
Thanks
