### ISSUE TITLE
Exception error when "Search for exactly similar characteristics (less false result)" is selected for the specific image and then click "Clear" button

### ISSUE THREAD

**Issue by Yoshitaka-Fukushima** [ORBNETSYS/i-PRO-Active-Guard-Public#89]
Test version : v1.5.1

**Procedure**
as titled.

**Phenomenon**
Message dialog is shown at first.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/0299ef91-3a1a-40f9-984e-0ea47820f60f)

After closing dialog and click "Clear" button, exception error occurs.

![image](https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/f3e4ae42-d713-474e-b590-e6c54b937ece)

************** Outer Exception **************Exception type:System.NullReferenceExceptionException message:Object reference not set to an instance of an object.Exception source:ActiveGuardMilestonePluginsException Target Site: Btn_ClearFilterFace_Click   at ActiveGuardMilestonePlugins.Client.ActiveGuardSearch.Btn_ClearFilterFace_Click(Object sender, RoutedEventArgs e) in C:\Users\ericb\source\repos\ORBNETSYS\i-PRO Active Guard\ActiveGuardMilestonePlugins\Client\ActiveGuardSearch.xaml.cs:line 2978   at ActiveGuardMilestonePlugins.Client.ActiveGuardSearch.Btn_FiltersClear_Click(Object sender, RoutedEventArgs e) in C:\Users\ericb\source\repos\ORBNETSYS\i-PRO Active Guard\ActiveGuardMilestonePlugins\Client\ActiveGuardSearch.xaml.cs:line 1890   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.Controls.Primitives.ButtonBase.OnClick()   at System.Windows.Controls.Button.OnClick()   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)   at System.Windows.Input.InputManager.ProcessStagingArea()   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************Date and time:	9/28/2023 4:14:50 PMMachine Name:	DESKTOP-3QVR4SBProcessors count:	12OS version:	Microsoft Windows NT 6.2.9200.064 bit OS:	True64 bit process:	TrueIP address:	fe80::e492:f06d:b63a:2d6%4 (DESKTOP-3QVR4SB)Current user:	DESKTOP-3QVR4SB\MilestonePC

@EricBourque 
It seems it depends on the detected value of the thumbnail and it is difficult for you to reproduce.
If needed, we will prepare remote connection.

**Comment by EricBourque** [comment]
Fixed in 1.5.2. We found the search item was being set to NULL if there were no attributes and it caused a chain effect.

**Comment by Yoshitaka-Fukushima** [comment]
@EricBourque 
Not fixed in v1.5.2.
Exception error occurs when we do similar procedure.

Video file shows details.

https://github.com/ORBNETSYS/i-PRO-Active-Guard-Public/assets/102282918/35b8b093-6f7b-4e77-be6a-327c61b5a6bd



************** Outer Exception **************
Exception type:System.NullReferenceException
Exception message:Object reference not set to an instance of an object.
Exception source:ActiveGuardMilestonePlugins
Exception Target Site: CB_PeopleHairGray_CheckChanged
   at ActiveGuardMilestonePlugins.Client.ActiveGuardSearch.CB_PeopleHairGray_CheckChanged(Object sender, RoutedEventArgs e) in C:\Users\ericb\source\repos\ORBNETSYS\i-PRO Active Guard\ActiveGuardMilestonePlugins\Client\ActiveGuardSearch.xaml.cs:line 3398
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ToggleButton.OnIsCheckedChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetCurrentValueInternal(DependencyProperty dp, Object value)
   at System.Windows.Controls.Primitives.ToggleButton.OnToggle()
   at System.Windows.Controls.Primitives.ToggleButton.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

************** System Info **************
Date and time:	10/2/2023 11:18:21 AM
Machine Name:	DESKTOP-3QVR4SB
Processors count:	12
OS version:	Microsoft Windows NT 6.2.9200.0
64 bit OS:	True
64 bit process:	True
IP address:	fe80::e492:f06d:b63a:2d6%4 (DESKTOP-3QVR4SB)
Current user:	DESKTOP-3QVR4SB\MilestonePC

**Comment by EricBourque** [comment]
Thank you for sharing video, re-uploaded 1.5.2 with a patch.
